Added dockerfile
Stella-Center/jitsi-meet-custom pull request #1
Opened 2024-03-29 15:03 UTC by nazar-h

2024-04-04 15:46 UTC, baminou requested changes

2024-04-04 15:46 UTC, baminou commented on images/favicon.ico
We would like to keep the default Volume way to update the favicon, we don't want to hardcode it

2024-04-04 15:46 UTC, baminou commented on title.html
title.html can be overwritten using Volumes, we don't want to hardcode this part, but instead keep on using the volume way of doing it.

2024-04-04 18:54 UTC, nazar-h commented on title.html
Done! TY!

2024-04-05 14:52 UTC, baminou approved these changes

2024-04-05 14:54 UTC, baminou approved these changes

2024-04-05 14:54 UTC, merged